[package]
name = "ledger_manager_cli"
version = "0.1.0"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]

edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
ledger_manager = { path = "../ledger_manager", version = "0.1.0" }
bitbox_manager = { path = "../bitbox_manager", version = "0.1.0" }
hex = "0.4"
